FROM node:8

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY ./server/package.json /usr/src/app/package.json
COPY ./server/server.js /usr/src/app/server/server.js
COPY ./config /usr/src/app/config
COPY ./model /usr/src/app/model
RUN npm install
RUN npm install nodemon -g

EXPOSE 3001

CMD ["nodemon", "server/server.js"]

